### ISSUE TITLE
Change recipe source to be GitLab?

### ISSUE THREAD

**Issue by matthewfeickert** [conda-forge/pythia8-feedstock#40]
@conda-forge/pythia8 Currently the source for the conda-forge recipe is grabbed from the [website release page](https://pythia.org/releases/)

https://github.com/conda-forge/pythia8-feedstock/blob/3d7d3e1f57334771b4ca3124bde73d423b2d54bb/recipe/meta.yaml#L9-L11

Would it make more sense to have it be from the GitLab source repository https://gitlab.com/Pythia8/releases? Or do the PYTHIA8 devs do any metadata revisions when generating the release artifacts that get put up on the website?

**Comment by chrisburr** [comment]
Sounds good to me, I think that repo didn't exist when this was set up.
